name: nbase

services:
  nbase:
    image: nbase:1.0
    container_name: nbase
    ports:
      - "${NEO4J_PORT_HTTP}:7474"
      - "${NEO4J_PORT_BOLT}:7687"
    environment:
      NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD}"
    volumes:
      - nbase-data:/data
      - nbase-logs:/logs

volumes:
  nbase-data:
    external: true
  nbase-logs:
    external: true
